### PR TITLE
Fix uninlining return values of method references and lambdas. Closes #17

### LINKED ISSUE #17: Constant resolution for lambda impl methods
From FabricMC/yarn#2553, it seems that lambda methods currently aren't resolved for unpicking. I forgot where the related unpick code is, but we can just probably visit the invoke dynamic handles (bootstrap method referred in indy bytecode) and unpick the linked synthetic methods.

### PR DESCRIPTION
**Pull request by Daomephsta**
This required a lot of changes. ConstantUninliner now takes class names instead of class nodes. It resolves the names into nodes via a class resolver (required to cache the nodes), allowing it to make changes to additional classes beyond the class it was asked to transform. Only the requested class is returned from `transform`, any other changed classes will be returned when their transformation is requested.

### CODE REVIEW

File: unpick-cli/src/main/java/daomephsta/unpick/cli/Main.java [hunk 1]
```diff
@@ -75,11 +81,8 @@ private static void unpick(Path inputJar, Path outputJar, Path unpickDefinition,
                     InputStream inputStream = jarFile.getInputStream(entry);
 
                     if (entry.getName().endsWith(".class")) {
-                        ClassReader classReader = new ClassReader(inputStream);
-                        ClassNode classNode = new ClassNode();
-                        classReader.accept(classNode, 0);
-
-                        uninliner.transform(classNode);
+                        String internalName = entry.getName().substring(0, entry.getName().length() - ".class".length());
```
Comment (Daomephsta) [inline unpick-cli/src/main/java/daomephsta/unpick/cli/Main.java:84]: I'm unsure if this correctly converts from ZIP entry path to class internal name. I would appreciate a second opinion.
